### ISSUE TITLE
Issue reported by Xcode when using SentimentPolarity

### ISSUE THREAD

**Issue by ccabanero** [SwiftBrain/awesome-CoreML-models#15]
Hello,

I am using Xcode 9 beta 5.  

When adding the SentimentPolarity.mlmodel to my Xcode project, I receive the following reported in the Issues section:
There was an problem decoding this CoreML document validator error: Description of multiarray feature '__feature_vector__' has an invalid or unspecified dataType. It must be specified as DOUBLE, FLOAT32 or INT32

I have attached a screenshot too:
![screen shot 2017-08-12 at 8 18 05 am](https://user-images.githubusercontent.com/1209057/29241848-036b26bc-7f37-11e7-856a-30ffba6f55e8.png)

Thank you for your work on this repo.

**Comment by ph1ps** [comment]
@ccabanero I will fix this ASAP, this is just an incompatibility issue.

**Comment by hsin919** [comment]
hi @ph1ps & @ccabanero  this issue should be fixed. FYI.

**Comment by ph1ps** [comment]
@hsin919 Thanks for noticing!
